### ISSUE TITLE
Add setup.py and publish package on pypi

### ISSUE THREAD

**Issue by faroit** [alicia-ziying-yang/conTEXT-explorer#15]
Given that the software has certain specific python requirements, I suggest to package the software as a proper python package and define the python requirements there. 

This issue is part of a JOSS review: https://github.com/openjournals/joss-reviews/issues/3347

**Comment by alicia-ziying-yang** [comment]
Hi @faroit , I have created a setup.py file in the root, and update the installation info in README.md.
But we are not sure if we want to publish the current version to pypi. Thus I create a todo issue #16 .
Thanks for your suggestion!
