### ISSUE TITLE
Relax python requirement

### ISSUE THREAD

**Issue by faroit** [alicia-ziying-yang/conTEXT-explorer#17]
even though the installation issue is fixed in #15 I would suggest not tp freeze python to `python_requires='==3.7.5',` but instead find out the supported range of python versions to identify the problematic dependencies (and in turns fix the code support newer dependencies later)

https://github.com/openjournals/joss-reviews/issues/3347

**Comment by alicia-ziying-yang** [comment]
as we used a lot of packages that has version clashes with each other... for now, can only be put into wish list.

**Comment by faroit** [comment]
> as we used a lot of packages that has version clashes with each other... for now, can only be put into wish list.

in that case i would suggest to add a conda environment file and a docker installation method

**Comment by alicia-ziying-yang** [comment]
I do not use docker, but can provide conda environment file: https://github.com/alicia-ziying-yang/conTEXT-explorer/blob/main/ce-env.yml

**Comment by faroit** [comment]
> I do not use docker, but can provide conda environment file: https://github.com/alicia-ziying-yang/conTEXT-explorer/blob/main/ce-env.yml

just tried this, please also add `pip` to the conda dependencies

```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

**Comment by alicia-ziying-yang** [comment]
Ah, yes, fixed that by moving the pip to the front!

**Comment by faroit** [comment]
@alicia-ziying-yang i can confirm that the environment works fine
