### ISSUE TITLE
[JOSS] Add automated unit tests

### ISSUE THREAD

**Issue by faroit** [alicia-ziying-yang/conTEXT-explorer#2]
As part of the JOSS review, I was checking if the software has automated tests included which currently is not the case. 

The JOSS guidelines state: 

> Authors are strongly encouraged to include an automated test suite covering the core functionality of their software.

>     Good: An automated test suite hooked up to an external service such as Travis-CI or similar
>    OK: Documented manual steps that can be followed to objectively check the expected functionality of the software (e.g., a sample input file to assert behavior)
>     Bad (not acceptable): No way for you, the reviewer, to objectively assess whether the software works

https://github.com/openjournals/joss-reviews/issues/3347

**Comment by alicia-ziying-yang** [comment]
hi @faroit, we have a small example included in the software. If you (or users) install our software, and run it for the first time, you could see that there is an existing corpus called "sample_data" in the dropdown of the corpus, and a saved analysis "SSM test" in the analysis dropdown. Users could use it to explore the core functions of software.
We have mentioned this example in the README "How to use" section, after "Run the app".

If you have any further question, please let me know. Happy to solve.

Thank you.

**Comment by alicia-ziying-yang** [comment]
Hi @faroit,
Have done with Travis-CI, and have attached the build-pass badge to the README.
Please check.

Thank you!

**Comment by faroit** [comment]
@alicia-ziying-yang thanks for adding this. For now, this only tests of the installation routine will pass and the software can be started. I suggest you also add some tests that test the functionality of the software and the data processing:

I guess https://dash.plotly.com/testing this would be a good start to read about testing with dash

**Comment by alicia-ziying-yang** [comment]
Hi @faroit,

Thanks for pointing out. Now I have added some test cases in https://github.com/alicia-ziying-yang/conTEXT-explorer/blob/main/test_cases.py
and change the Travis-CI .yml file.

Please check the newest build: https://travis-ci.com/github/alicia-ziying-yang/conTEXT-explorer

Thank you.

**Comment by faroit** [comment]
@alicia-ziying-yang wow, this looks great. Happy to close this now!
