### ISSUE TITLE
Suggestions for ConTEXT-explorer paper

### ISSUE THREAD

**Issue by baileythegreen** [alicia-ziying-yang/conTEXT-explorer#4]
I agree with the suggestion from #1 about moving the Key Features heading to before line 40 and renaming the third part.

## Typos
- Lines 15, 25: corpora is misspelled
- Line 19: original is misspelled
- Line 26: usually is misspelled
- Line 28: interested is misspelled
- Line 29, footnote 1: multiple is misspelled
- Line 63: concept is misspelled
- Figure 4: missing period at end of the caption

## Other things that need fixing
- Line 117: references Section 3.2, but your sections are not numbered

JOSS Reference: openjournals/joss-reviews#3347

**Comment by baileythegreen** [comment]
I tried to push these changes on a different branch, so I could create a pull request, but I'm not able to do so.

**Comment by alicia-ziying-yang** [comment]
Hi @baileythegreen , thank you so much for pointing them out. 
I have fixed the issues you mentioned, and pushed to the repo (paper.md).
